### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by adaojunior** [ntaoo/material2_dart#1]
Hi, thanks for the work,
I noticed your work and since I was working on porting material design for dart as well I was wondering if you want to work together on this project ?
Here's the link of the repository: [adaojunior/md](https://github.com/adaojunior/md)
 I look forward to hearing from you soon.
If you are in the dartlang slack you can find me at `adaojunior`.

**Comment by ntaoo** [comment]
Hi, thank you for introducing your work, @adaojunior. I am happy to know your porting work.

Looks like justindujardin/ng2-material and angular/material2 are both built for material design components, some pieces of the design looks same, but they are the different project.

It would be meaningful that there are the different approaches for md components. I continue to work for this repo for the time being.
