### ISSUE TITLE
How do I get this to run on windows

### ISSUE THREAD

**Issue by jrote1** [ntaoo/material2_dart#35]
I have been trying to get this to run on windows but without much success, do you know how I would go about it?

**Comment by ntaoo** [comment]
(The discussion has paused on the Gitter. Actually, I didn't try this library on Windows and may have some fault on the platform. Needs more feedback but close it for now.)

**Comment by jrote1** [comment]
@ntaoo I did eventually get this to work on windows with alot of work. But this latest update has removed the problem, thanks for your good work

**Comment by ntaoo** [comment]
I didn't test it in a real situation (non-relative path) so I didn't notice the problems. Thank you for your try and patience!
