### ISSUE TITLE
pub repo is faulty can't see version 0.4.1

### ISSUE THREAD

**Issue by sandrobilbeisi** [ntaoo/material2_dart#42]
pub repo is faulty
can't see version 0.4.1

from pub spec.yam : 

> material2_dart: ^0.4.1
or
> material2_dart: '0.4.1'    

pub get yields:
> Package material2_dart has no versions that match 0.4.1 derived from:
> - angular2_mynew_example depends on version 0.4.1

**Comment by ntaoo** [comment]
I guess some dependencies' version constraint  is narrow in your pubspec.
In the following example, the package can be downloaded.

```
  angular2: ^2.0.0
  material2_dart: ^0.4.1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
```

I could widen package:quiver's constraint in material2_dart.

**Comment by sandrobilbeisi** [comment]
I want to import a few of your components into a project that already has official components
 dependencies:
 

>  angular2: ^2.0.0
>   angular2_components: ^0.1.0
>   browser: ^0.10.0
>   material2_dart: >=0.4.0
>   dart_to_js_script_rewriter: ^1.0.1
> 
> dev_dependencies:
>   webdriver: ^1.2.1

**Comment by sandrobilbeisi** [comment]
I then tried to use a local copy of material2_dart

> dependencies:
> ...
>   material2_dart:
>     path: /Users/utente/Desktop/ng2/material2_dart-master
>   dart_to_js_script_rewriter: ^1.0.1

and I get this error:

> Incompatible version constraints on quiver:
> - angular2_components 0.1.0 depends on version >=0.22.0 <0.24.0
> - material2_dart 0.4.1 depends on version ^0.24.0
>

**Comment by ntaoo** [comment]
Thank you for the sharing. I will relax the quiver's version constraint and publish soon.

**Comment by ntaoo** [comment]
@sandrobilbeisi I have upgraded this package. Ping me if you have the same problem with the latest one.
