### ISSUE TITLE
Support AngularDart v2.1.0.

### ISSUE THREAD

**Issue by ntaoo** [ntaoo/material2_dart#44]

**Comment by daniel-v** [comment]
I am getting these kinds of errors in the browser:

`ORIGINAL EXCEPTION: No provider for Renderer!`

**Comment by daniel-v** [comment]
Do I understand it correctly that what needs to be done here is that `Renderer` invocations need to be replaced with dart:html calls?

If so, I can possibly help with a couple of pull requests.

**Comment by ntaoo** [comment]
Yes, it should be an easy fix with "dart:html".
Your pull request is welcome!
